---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function fzf(p)
  return {
    FzfLuaNormal = { fg = p.fg0, bg = p.bg1 },
    FzfLuaBorder = { fg = p.fg3, bg = p.bg1 },
    FzfLuaTitle = { fg = p.accent, bg = p.bg1, italic = true },
    FzfLuaTitleFlags = { fg = p.fg2, bg = p.bg1 },
    FzfLuaPreviewNormal = { fg = p.fg0, bg = p.bg0 },
    FzfLuaPreviewBorder = { fg = p.fg3, bg = p.bg0 },
    FzfLuaPreviewTitle = { fg = p.accent2, bg = p.bg0, italic = true },
    FzfLuaCursor = { link = 'Cursor' },
    FzfLuaCursorLine = { bg = p.sel },
    FzfLuaCursorLineNr = { link = 'CursorLineNr' },
    FzfLuaSearch = { link = 'Search' },
    FzfLuaScrollBorderEmpty = { fg = p.fg3, bg = p.bg1 },
    FzfLuaScrollBorderFull = { fg = p.accent, bg = p.bg1 },
    FzfLuaScrollFloatEmpty = { bg = p.bg2 },
    FzfLuaScrollFloatFull = { bg = p.accent },
    FzfLuaHelpNormal = { fg = p.fg0, bg = p.bg0 },
    FzfLuaHelpBorder = { fg = p.fg3, bg = p.bg0 },
    FzfLuaHeaderBind = { fg = p.accent2 },
    FzfLuaHeaderText = { fg = p.blue },
    FzfLuaPathColNr = { fg = p.fg3 },
    FzfLuaPathLineNr = { fg = p.green },
    FzfLuaBufName = { fg = p.fg1 },
    FzfLuaBufId = { link = 'FzfLuaBufNr' },
    FzfLuaBufNr = { fg = p.fg3 },
    FzfLuaBufLineNr = { link = 'LineNr' },
    FzfLuaBufFlagCur = { fg = p.accent },
    FzfLuaBufFlagAlt = { fg = p.accent2 },
    FzfLuaTabTitle = { fg = p.accent, italic = true },
    FzfLuaTabMarker = { fg = p.accent2 },
    FzfLuaDirIcon = { fg = p.blue },
    FzfLuaDirPart = { fg = p.fg2 },
    FzfLuaFilePart = { fg = p.fg0 },
    FzfLuaLiveSym = { fg = p.accent2 },
    FzfLuaLivePrompt = { fg = p.accent },
    FzfLuaCmdEx = { fg = p.accent2 },
    FzfLuaCmdBuf = { fg = p.green },
    FzfLuaCmdGlobal = { fg = p.blue },
    FzfLuaFzfBorder = { link = 'FzfLuaBorder' },
    FzfLuaFzfCursorLine = { link = 'FzfLuaCursorLine' },
    FzfLuaFzfGutter = { bg = p.bg1 },
    FzfLuaFzfHeader = { fg = p.fg2 },
    FzfLuaFzfInfo = { fg = p.fg3 },
    FzfLuaFzfMarker = { fg = p.accent2 },
    FzfLuaFzfMatch = { fg = p.accent, italic = true },
    FzfLuaFzfNormal = { link = 'FzfLuaNormal' },
    FzfLuaFzfPointer = { fg = p.accent },
    FzfLuaFzfPrompt = { fg = p.accent },
    FzfLuaFzfQuery = { fg = p.fg0 },
    FzfLuaFzfScrollbar = { fg = p.accent, bg = p.bg1 },
    FzfLuaFzfSeparator = { fg = p.fg3, bg = p.bg1 },
    FzfLuaFzfSpinner = { fg = p.accent },
    FzfLuaBackdrop = { bg = p.bg0 },
  }
end

return fzf
