---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function nvimtree(p)
  return {
    NvimTreeNormal = { fg = p.fg0, bg = p.bg1 },
    NvimTreeNormalNC = { fg = p.fg0, bg = p.bg1 },
    NvimTreeNormalFloat = { link = 'NormalFloat' },
    NvimTreeNormalFloatBorder = { link = 'FloatBorder' },
    NvimTreeWinSeparator = { fg = p.bg4, bg = p.bg1 },
    NvimTreeEndOfBuffer = { fg = p.bg1 },
    NvimTreeCursorLine = { bg = p.bg4 },
    NvimTreeLineNr = { link = 'LineNr' },
    NvimTreePopup = { link = 'Pmenu' },
    NvimTreeSignColumn = { link = 'SignColumn' },
    NvimTreeCursorColumn = { link = 'CursorColumn' },
    NvimTreeCursorLineNr = { link = 'CursorLineNr' },
    NvimTreeStatusLine = { link = 'StatusLine' },
    NvimTreeStatusLineNC = { link = 'StatusLineNC' },
    NvimTreeRootFolder = { fg = p.accent, italic = true },
    NvimTreeFolderName = { fg = p.blue },
    NvimTreeFolderIcon = { fg = p.blue },
    NvimTreeOpenedFolderIcon = { link = 'NvimTreeFolderIcon' },
    NvimTreeClosedFolderIcon = { link = 'NvimTreeFolderIcon' },
    NvimTreeFolderArrowOpen = { fg = p.fg3 },
    NvimTreeFolderArrowClosed = { fg = p.fg3 },
    NvimTreeOpenedFolderName = { fg = p.blue, italic = true },
    NvimTreeEmptyFolderName = { fg = p.fg3 },
    NvimTreeSymlinkFolderName = { fg = p.purple },
    NvimTreeFileIcon = { fg = p.fg0 },
    NvimTreeExecFile = { fg = p.green, italic = true },
    NvimTreeSpecialFile = { fg = p.accent2 },
    NvimTreeSymlink = { fg = p.purple },
    NvimTreeSymlinkIcon = { link = 'NvimTreeSymlink' },
    NvimTreeIndentMarker = { fg = p.fg3 },
    NvimTreeImageFile = { fg = p.purple },
    NvimTreeWindowPicker = { fg = p.bg3, bg = p.accent, italic = true },
    NvimTreeLiveFilterPrefix = { link = 'PreProc' },
    NvimTreeLiveFilterValue = { link = 'Search' },
    NvimTreeCopiedHL = { fg = p.green },
    NvimTreeCutHL = { fg = p.yellow },
    NvimTreeBookmarkIcon = { fg = p.accent },
    NvimTreeBookmarkHL = { fg = p.accent, bg = p.bg4 },
    NvimTreeHiddenDisplay = { fg = p.fg3 },
    NvimTreeHiddenIcon = { fg = p.fg3 },
    NvimTreeHiddenFileHL = { fg = p.fg3 },
    NvimTreeHiddenFolderHL = { fg = p.fg3 },
    -- Git icon groups (current canonical names)
    NvimTreeGitDirtyIcon = { fg = p.yellow },
    NvimTreeGitStagedIcon = { fg = p.green },
    NvimTreeGitMergeIcon = { fg = p.accent },
    NvimTreeGitRenamedIcon = { fg = p.purple },
    NvimTreeGitNewIcon = { fg = p.green },
    NvimTreeGitDeletedIcon = { fg = p.red },
    NvimTreeGitIgnoredIcon = { fg = p.fg3 },
    NvimTreeDiagnosticErrorIcon = { fg = p.red },
    NvimTreeDiagnosticWarnIcon = { fg = p.yellow },
    NvimTreeDiagnosticInfoIcon = { fg = p.blue },
    NvimTreeDiagnosticHintIcon = { fg = p.cyan },
    -- Modified/opened icons
    NvimTreeModifiedIcon = { fg = p.yellow },
    NvimTreeOpenedHL = { fg = p.fg0, italic = true },
    -- *HL variants: activated by renderer.highlight_git = 'name'
    NvimTreeGitFileDirtyHL = { link = 'NvimTreeGitDirtyIcon' },
    NvimTreeGitFileStagedHL = { link = 'NvimTreeGitStagedIcon' },
    NvimTreeGitFileMergeHL = { link = 'NvimTreeGitMergeIcon' },
    NvimTreeGitFileRenamedHL = { link = 'NvimTreeGitRenamedIcon' },
    NvimTreeGitFileNewHL = { link = 'NvimTreeGitNewIcon' },
    NvimTreeGitFileDeletedHL = { link = 'NvimTreeGitDeletedIcon' },
    NvimTreeGitFileIgnoredHL = { link = 'NvimTreeGitIgnoredIcon' },
    NvimTreeGitFolderDirtyHL = { link = 'NvimTreeGitFileDirtyHL' },
    NvimTreeGitFolderStagedHL = { link = 'NvimTreeGitFileStagedHL' },
    NvimTreeGitFolderMergeHL = { link = 'NvimTreeGitFileMergeHL' },
    NvimTreeGitFolderRenamedHL = { link = 'NvimTreeGitFileRenamedHL' },
    NvimTreeGitFolderNewHL = { link = 'NvimTreeGitFileNewHL' },
    NvimTreeGitFolderDeletedHL = { link = 'NvimTreeGitFileDeletedHL' },
    NvimTreeGitFolderIgnoredHL = { link = 'NvimTreeGitFileIgnoredHL' },
    -- *HL variants: activated by renderer.highlight_modified / highlight_opened_files = 'name'
    NvimTreeModifiedFileHL = { link = 'NvimTreeModifiedIcon' },
    NvimTreeModifiedFolderHL = { link = 'NvimTreeModifiedIcon' },
    -- *HL variants: activated by renderer.highlight_diagnostics = 'name'
    NvimTreeDiagnosticErrorFileHL = { link = 'DiagnosticError' },
    NvimTreeDiagnosticWarnFileHL = { link = 'DiagnosticWarn' },
    NvimTreeDiagnosticInfoFileHL = { link = 'DiagnosticInfo' },
    NvimTreeDiagnosticHintFileHL = { link = 'DiagnosticHint' },
    NvimTreeDiagnosticErrorFolderHL = { link = 'NvimTreeDiagnosticErrorFileHL' },
    NvimTreeDiagnosticWarnFolderHL = { link = 'NvimTreeDiagnosticWarnFileHL' },
    NvimTreeDiagnosticInfoFolderHL = { link = 'NvimTreeDiagnosticInfoFileHL' },
    NvimTreeDiagnosticHintFolderHL = { link = 'NvimTreeDiagnosticHintFileHL' },
  }
end

return nvimtree
